image: WMF 5
version: 1.0.0 (Build {build})

environment: 
  USERS_V8_1C_LOGIN: 20005700694
  USERS_V8_1C_PASSWORD:
    secure: hXnd+ZRsLxcdiBwhBbkzSob372B0Ce11cFzHMkmAcwU=
  NCSM_VPN_LOGIN: sergei.s.betke@csm.nov.ru
  NCSM_VPN_PASSWORD:
    secure: JLKHHenr4eKeTuNMhx2A1R1OjBiW351fa5233PwjJC4=

install:
  - cmd: GitVersion /output buildserver
  - ps: .\install\install.ps1 -ErrorAction Stop -InformationAction Continue -Verbose
  - ps: >-
      Add-VpnConnection -Name 'NCSM' -ServerAddress 'gate.csm.nov.ru' -TunnelType Pptp -Force;
      Add-VpnConnectionRoute -ConnectionName 'NCSM' -DestinationPrefix '192.168.100.0/24';
      $p = Start-Process rasdial -ArgumentList "NCSM $( $env:NCSM_VPN_LOGIN ) `"$( $env:NCSM_VPN_PASSWORD )`"" -PassThru -Wait -NoNewWindow;

build_script:
  - cmd: ping 192.168.100.4
  - cmd: ping srv-mgmt.csm.nov.ru
